### ISSUE TITLE
Layout problem

### ISSUE THREAD

**Issue by BillyLiou** [noahgorstein/jqp#47] opened 2023-10-06 17:52 UTC
I use brew to install jqp
Although it can query as normal, but it shows like that.

<img width="1336" alt="image" src="https://github.com/noahgorstein/jqp/assets/41287035/201c92d7-90f5-4248-a67e-4d73dbe923e9">

Machine information:
MacOS: Sonoma 14.0
2.3 GHz 4 cores Intel Core i5

iTerm2: Build 3.4.21
jqp version: v0.5.0

Thanks

**Comment by noahgorstein** [comment] 2023-10-06 18:49
Unable to reproduce with jqp v0.5.0 on my M1 running MacOS Sonoma 14.0 with iTerm2 v3.4.21. 

Do you have the same issue with other terminal emulators like stock Terminal.app or other popular emulators like Alacritty and Kitty?

Additional, when you resize the window, does it "fix" the layout?

**Comment by lunrenyi** [comment] 2023-11-11 08:26
你好，我从 Release中 下载的 jqp_Linux_x86_64.tar.gz  也存在同样的问题，我使用的系统是 Ubuntu .

![1](https://github.com/noahgorstein/jqp/assets/87307989/7d759799-b87b-4975-b715-7c792eaa9232)
![2](https://github.com/noahgorstein/jqp/assets/87307989/3056d9ba-eb05-407f-8836-492e1fa6b278)

```bash
% ls -lh ./jqp_Linux_x86_64.tar.gz
-rw-rw-r-- 1 lunrenyi lunrenyi 4.2M 11月 11 16:06 ./jqp_Linux_x86_64.tar.gz
% file ./jqp                      
./jqp: ELF 64-bit LSB executable, x86-64, version 1 (SYSV), statically linked, Go BuildID=EjVwBSAm8-6gJX5kDXWx/iljnHxtlI61BLfikfIrl/4jjkrJGyLEE9nd4FgJGn/iXvxk5NH8Xzqihtr8Orp, stripped
% ./jqp -f ascii.json

```
![3](https://github.com/noahgorstein/jqp/assets/87307989/7c2726f8-c966-4eef-b289-4970808e40d2)

**Comment by noahgorstein** [comment] 2023-11-11 14:09
@lunrenyi check out this issue reported earlier in the year: https://github.com/noahgorstein/jqp/issues/6#issuecomment-1518503774

Can you see if specifying your `LANG` env variable as `en_US.UTF-8` fixes this?

**Comment by lunrenyi** [comment] 2023-11-12 12:28
@noahgorstein 指定LANG环境变量为en_US.UTF-8可以解决这个问题

![1](https://github.com/noahgorstein/jqp/assets/87307989/2b498963-1b62-4103-9e24-bb17454feed5)
![2](https://github.com/noahgorstein/jqp/assets/87307989/fd047f0d-73cb-4fb8-83d9-3637d2c14e46)

**Comment by noahgorstein** [comment] 2024-01-17 03:31
Appears to be resolved by setting the environment variable `LANG` to `en_US.UTF-8`.

**Closed by noahgorstein** 2024-01-17 03:31 UTC
Labels: bug
